//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urakawa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UrakawaSDK_core_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrakawaSDK_core_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("urakawa.UrakawaSDK.core.Lang", typeof(UrakawaSDK_core_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A party whose contribution to the publication is secondary to those named in dc:Creator.
        /// </summary>
        public static string Metadata_desc_dcContributor {
            get {
                return ResourceManager.GetString("Metadata_desc_dcContributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extent or scope of the content of the resource.
        /// </summary>
        public static string Metadata_desc_dcCoverage {
            get {
                return ResourceManager.GetString("Metadata_desc_dcCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names of primary author or creator of the intellectual content of the publication.
        /// </summary>
        public static string Metadata_desc_dcCreator {
            get {
                return ResourceManager.GetString("Metadata_desc_dcCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of publication of the DTB.
        /// </summary>
        public static string Metadata_desc_dcDate {
            get {
                return ResourceManager.GetString("Metadata_desc_dcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain text describing the publication&apos;s content.
        /// </summary>
        public static string Metadata_desc_dcDescription {
            get {
                return ResourceManager.GetString("Metadata_desc_dcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The standard or specification to which the DTB was produced.
        /// </summary>
        public static string Metadata_desc_dcFormat {
            get {
                return ResourceManager.GetString("Metadata_desc_dcFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string or number identifying the DTB.
        /// </summary>
        public static string Metadata_desc_dcIdentifier {
            get {
                return ResourceManager.GetString("Metadata_desc_dcIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of the content of the publication.
        /// </summary>
        public static string Metadata_desc_dcLanguage {
            get {
                return ResourceManager.GetString("Metadata_desc_dcLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agency responsible for making the DTB available.
        /// </summary>
        public static string Metadata_desc_dcPublisher {
            get {
                return ResourceManager.GetString("Metadata_desc_dcPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to a related resource.
        /// </summary>
        public static string Metadata_desc_dcRelation {
            get {
                return ResourceManager.GetString("Metadata_desc_dcRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about rights held in and over the DTB.
        /// </summary>
        public static string Metadata_desc_dcRights {
            get {
                return ResourceManager.GetString("Metadata_desc_dcRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to a resource (e.g., a print original, ebook, etc.) from which the DTB is derived. Best practice is to use the ISBN when available..
        /// </summary>
        public static string Metadata_desc_dcSource {
            get {
                return ResourceManager.GetString("Metadata_desc_dcSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The topic of the content of the publication.
        /// </summary>
        public static string Metadata_desc_dcSubject {
            get {
                return ResourceManager.GetString("Metadata_desc_dcSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of the DTB, including any subtitles.
        /// </summary>
        public static string Metadata_desc_dcTitle {
            get {
                return ResourceManager.GetString("Metadata_desc_dcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nature of the content of the DTB (recommended are Dublin Core keywords &quot;audio&quot;, &quot;text&quot;, and &quot;image&quot;).
        /// </summary>
        public static string Metadata_desc_dcType {
            get {
                return ResourceManager.GetString("Metadata_desc_dcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format in which the audio files in the DTB file set are written.
        /// </summary>
        public static string Metadata_desc_dtbAudioFormat {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbAudioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the general types of media used in the content of this DTB.
        /// </summary>
        public static string Metadata_desc_dtbMultimediaContent {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbMultimediaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the six types of DTB defined in the Structure Guidelines.
        /// </summary>
        public static string Metadata_desc_dtbMultimediaType {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbMultimediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the person whose recorded voice is embodied in the DTB.
        /// </summary>
        public static string Metadata_desc_dtbNarrator {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbNarrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fallback XSLT file.
        /// </summary>
        public static string Metadata_desc_dtbookXsltFallback {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbookXsltFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of first generation of the complete DTB, i.e. production completion date.
        /// </summary>
        public static string Metadata_desc_dtbProducedDate {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbProducedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the organization/production unit that created the DTB.
        /// </summary>
        public static string Metadata_desc_dtbProducer {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative integer value of the specific version of the DTB. Incremented each time the DTB is revised..
        /// </summary>
        public static string Metadata_desc_dtbRevision {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date associated with the specific dtb:revision.
        /// </summary>
        public static string Metadata_desc_dtbRevisionDate {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbRevisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes introduced in a specific dtb:revision.
        /// </summary>
        public static string Metadata_desc_dtbRevisionDescription {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbRevisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of publication of the resource (e.g., a print original, ebook, etc.) from which the DTB is derived.
        /// </summary>
        public static string Metadata_desc_dtbSourceDate {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbSourceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string describing the edition of the resource (e.g., a print original, ebook, etc.) from which the DTB is derived.
        /// </summary>
        public static string Metadata_desc_dtbSourceEdition {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbSourceEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agency responsible for making available the resource (e.g., a print original, ebook, etc.) from which the DTB is derived.
        /// </summary>
        public static string Metadata_desc_dtbSourcePublisher {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbSourcePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about rights held in and over the resource (e.g., a print original, ebook, etc.) from which the DTB is derived.
        /// </summary>
        public static string Metadata_desc_dtbSourceRights {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbSourceRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of the resource (e.g., a print original, ebook, etc.) from which the DTB is derived. To be used only if different from dc:Title.
        /// </summary>
        public static string Metadata_desc_dtbSourceTitle {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total playing time of all SMIL files comprising the content of the DTB.
        /// </summary>
        public static string Metadata_desc_dtbTotalTime {
            get {
                return ResourceManager.GetString("Metadata_desc_dtbTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A custom metadata item.
        /// </summary>
        public static string Metadata_desc_unrecognized {
            get {
                return ResourceManager.GetString("Metadata_desc_unrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the extension to the core Z39.86 specification.
        /// </summary>
        public static string Metadata_desc_z3986ExtensionVersion {
            get {
                return ResourceManager.GetString("Metadata_desc_z3986ExtensionVersion", resourceCulture);
            }
        }
    }
}
