//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewClass2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class NewSettings2 : global::System.Configuration.ApplicationSettingsBase {
        
        private static NewSettings2 defaultInstance = ((NewSettings2)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NewSettings2())));
        
        public static NewSettings2 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string2")]
        public string Class2Text {
            get {
                return ((string)(this["Class2Text"]));
            }
            set {
                this["Class2Text"] = value;
            }
        }
    }
}
