//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urakawa.daisy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UrakawaSDK_daisy_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrakawaSDK_daisy_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("urakawa.daisy.UrakawaSDK.daisy.Lang", typeof(UrakawaSDK_daisy_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files created.
        /// </summary>
        public static string AllFilesCreated {
            get {
                return ResourceManager.GetString("AllFilesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled XUK Saving..
        /// </summary>
        public static string CancelledXUKSaving {
            get {
                return ResourceManager.GetString("CancelledXUKSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting audio: [{0}].
        /// </summary>
        public static string ConvertingAudio {
            get {
                return ResourceManager.GetString("ConvertingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying audio: [{0}].
        /// </summary>
        public static string CopyingAudio {
            get {
                return ResourceManager.GetString("CopyingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating mp3 file [{0}] {1}.
        /// </summary>
        public static string CreateMP3File {
            get {
                return ResourceManager.GetString("CreateMP3File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating smil and ncx files.
        /// </summary>
        public static string CreateSmilAndNcxFiles {
            get {
                return ResourceManager.GetString("CreateSmilAndNcxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating audio file [{0}] {1}.
        /// </summary>
        public static string CreatingAudioFile {
            get {
                return ResourceManager.GetString("CreatingAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating EPUB files....
        /// </summary>
        public static string CreatingEPUB {
            get {
                return ResourceManager.GetString("CreatingEPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating EPUB zip: .
        /// </summary>
        public static string CreatingEPUBZip {
            get {
                return ResourceManager.GetString("CreatingEPUBZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating external files like .css, .dtd etc..
        /// </summary>
        public static string CreatingExternalFiles {
            get {
                return ResourceManager.GetString("CreatingExternalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating smil files {0} / {1}.
        /// </summary>
        public static string CreatingSmilFiles {
            get {
                return ResourceManager.GetString("CreatingSmilFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DTBook.xml file.
        /// </summary>
        public static string CreatingXMLFile {
            get {
                return ResourceManager.GetString("CreatingXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding audio: [{0}].
        /// </summary>
        public static string DecodingAudio {
            get {
                return ResourceManager.GetString("DecodingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in encoding {0}.
        /// </summary>
        public static string ErrorInEncoding {
            get {
                return ResourceManager.GetString("ErrorInEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import initialized..
        /// </summary>
        public static string ImportInitialized {
            get {
                return ResourceManager.GetString("ImportInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing import....
        /// </summary>
        public static string InitializeImport {
            get {
                return ResourceManager.GetString("InitializeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing content: [{0}].
        /// </summary>
        public static string ParsingContent {
            get {
                return ResourceManager.GetString("ParsingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing EPUB3 Media Overlay: [{0}].
        /// </summary>
        public static string ParsingMediaOverlay {
            get {
                return ResourceManager.GetString("ParsingMediaOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing metadata: [{0}].
        /// </summary>
        public static string ParsingMetadata {
            get {
                return ResourceManager.GetString("ParsingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing OPF: [{0}].
        /// </summary>
        public static string ParsingOPF {
            get {
                return ResourceManager.GetString("ParsingOPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing SMIL file [{2}] {0} / {1}....
        /// </summary>
        public static string ParsingSmilFile {
            get {
                return ResourceManager.GetString("ParsingSmilFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading XML document [{0}]....
        /// </summary>
        public static string ReadXMLDoc {
            get {
                return ResourceManager.GetString("ReadXMLDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving XUK....
        /// </summary>
        public static string SaveXUK {
            get {
                return ResourceManager.GetString("SaveXUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving XUK file....
        /// </summary>
        public static string SavingXUKFile {
            get {
                return ResourceManager.GetString("SavingXUKFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializing the document object model from the Urakawa SDK as XML content into a XUK file....
        /// </summary>
        public static string SerializeDOMIntoXUKFile {
            get {
                return ResourceManager.GetString("SerializeDOMIntoXUKFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform complete.
        /// </summary>
        public static string TransformComplete {
            get {
                return ResourceManager.GetString("TransformComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB of {1} MB.
        /// </summary>
        public static string TreeNode_SizeInfo {
            get {
                return ResourceManager.GetString("TreeNode_SizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing file: [{0}].
        /// </summary>
        public static string Unzipping {
            get {
                return ResourceManager.GetString("Unzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML document loaded [{0}]..
        /// </summary>
        public static string XmlDocLoaded {
            get {
                return ResourceManager.GetString("XmlDocLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUK Saved..
        /// </summary>
        public static string XUKSaved {
            get {
                return ResourceManager.GetString("XUKSaved", resourceCulture);
            }
        }
    }
}
