//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaisyToXuk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaisyToXuk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- DTBook DTD v2005-1  2005-06-26
        ///file: dtbook-2005-1.dtd   
        /// 
        ///The following identifiers apply to this DTD:    
        ///  &quot;-//NISO//DTD dtbook 2005-1//EN&quot;
        ///  &quot;http://www.daisy.org/z3986/2005/dtbook-2005-1.dtd&quot;&gt;
        ///--&gt;
        ///
        ///
        ///
        ///&lt;!--HB: 2004-03-25 - 2004-04-28 Changes that update dtbook 1.1.0 Document
        ///    Type Declaration: 
        ///    When the change date is followed by &quot;nn:&quot; or &quot;nna&quot; that represents the
        ///    number/letter code on the change list supplied from Michael Moodie on
        ///    that date. Additional changes not so  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dtbook_2005_1 {
            get {
                return ResourceManager.GetString("dtbook_2005_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- DTBook DTD v2005-2  2006-09-08
        ///file: dtbook-2005-2.dtd   
        /// 
        ///The following identifiers apply to this DTD:    
        ///  &quot;-//NISO//DTD dtbook 2005-2//EN&quot;
        ///  &quot;http://www.daisy.org/z3986/2005/dtbook-2005-2.dtd&quot;&gt;
        ///--&gt;
        ///
        ///&lt;!--jpritchett@rfbd.org:  2006-09-08  Changes that update to version 2005-2, per committee decisions 
        ///    Issue numbers noted in change log below refer to Z39.86 issue tracker at 
        ///    http://www.daisy.org/z3986/issues/ 
        ///--&gt;
        ///
        ///&lt;!--HB: 2004-03-25 - 2004-04-28 Changes that update dtbook 1.1.0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dtbook_2005_2 {
            get {
                return ResourceManager.GetString("dtbook_2005_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- DTBook DTD v2005-3  2007-12-19
        ///file: dtbook-2005-3.dtd   
        /// 
        ///The following identifiers apply to this DTD:    
        ///  &quot;-//NISO//DTD dtbook 2005-3//EN&quot;
        ///  &quot;http://www.daisy.org/z3986/2005/dtbook-2005-3.dtd&quot;&gt;
        ///--&gt;
        ///
        ///&lt;!--jpritchett@rfbd.org:  2007-12-19  Changes that update to version 2005-3, per committee decisions
        ///    Issue numbers noted in change log below refer to Z39.86 issue tracker at 
        ///    http://www.daisy.org/z3986/issues/ 
        ///--&gt;
        ///
        ///&lt;!--jpritchett@rfbd.org:  2006-09-08  Changes that update to versi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dtbook_2005_3 {
            get {
                return ResourceManager.GetString("dtbook_2005_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--SMIL 2.0 DTB-specific DTD Version 2005-1 2005-06-26
        ///file: dtbsmil-2005-1.dtd 
        ///
        ///Authors: Michael Moodie, Tom McLaughlin, Lloyd Rasmussen, Thomas Kjellberg Christensen, 
        ///Laust Skat Nielsen
        ///Change list:
        ///2002-02-12  M. Moodie. Dropped version attribute on smil element, as this attribute 
        ///is not present in SMIL specification.
        ///2004-02-19  L.S. Nielsen. made clipBegin and clipEnd REQUIRED on audio element
        ///2004-03-02  L.S. Nielsen. Dropped second statement in comment that preceeds declaration 
        ///of ELEM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dtbsmil_2005_1 {
            get {
                return ResourceManager.GetString("dtbsmil_2005_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--SMIL 2.0 DTB-specific DTD Version 2005-2 2006-09-07
        ///file: dtbsmil-2005-2.dtd 
        ///
        ///Authors: Michael Moodie, Tom McLaughlin, Lloyd Rasmussen, Thomas Kjellberg Christensen, 
        ///Laust Skat Nielsen
        ///Change list:
        ///2002-02-12  M. Moodie. Dropped version attribute on smil element, as this attribute 
        ///is not present in SMIL specification.
        ///2004-02-19  L.S. Nielsen. made clipBegin and clipEnd REQUIRED on audio element
        ///2004-03-02  L.S. Nielsen. Dropped second statement in comment that preceeds declaration 
        ///of ELEM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dtbsmil_2005_2 {
            get {
                return ResourceManager.GetString("dtbsmil_2005_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- MathML 2.0 DTD  ....................................................... --&gt;
        ///&lt;!-- file: mathml2.dtd
        ///--&gt;
        ///
        ///&lt;!-- MathML 2.0 DTD
        ///
        ///     This is the Mathematical Markup Language (MathML) 2.0, an XML
        ///     application for describing mathematical notation and capturing
        ///     both its structure and content.
        ///
        ///     Copyright &amp;#xa9; 1998-2003 W3C&amp;#xae; (MIT, ERCIM, Keio), All Rights 
        ///     Reserved. W3C liability, trademark, document use and software
        ///     licensing rules apply. 
        ///
        ///     Permission to use, copy, modify a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mathml2 {
            get {
                return ResourceManager.GetString("mathml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- NCX 2005-1 DTD  2005-06-26
        ///file: ncx-2005-1.dtd                                 
        ///
        ///  Authors: Mark Hakkinen, George Kerscher, Tom McLaughlin, James Pritchett, and Michael Moodie
        ///  Change list:
        ///  2002-02-12 M. Moodie. Changed content model of navLabel element to eliminate ambiguity.
        ///  2002-02-27 M. Moodie. Grammatical changes suggested by editor.
        ///  2004-03-31 J. Pritchett.  Various changes per the 2004 change list:
        ///            - Changed internal version numbers from 1.1.0 to 1.2.0
        ///            -  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ncx_2005_1 {
            get {
                return ResourceManager.GetString("ncx_2005_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///
        ///Title:
        ///
        ///     The Package Document Type Definition (DTD) for the Open
        ///     eBook Publication Structure Version 1.2
        ///
        ///
        ///Version:
        ///
        ///     1.2
        ///
        ///
        ///Revision:
        ///
        ///     20020930-x  (supercedes 20020605-x)
        ///
        ///
        ///Revision History Note:
        ///
        ///     This revision, 20020930-x, which supercedes the prior revision
        ///     20020605-x, solely updates the email addresses within this
        ///     comment prologue. No changes whatsover were made to the parsed
        ///     content of this DTD.
        ///
        ///
        ///Previous Released Version:
        ///
        ///     1. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string oebpkg12 {
            get {
                return ResourceManager.GetString("oebpkg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ....................................................................... --&gt;
        ///&lt;!-- XHTML 1.1 plus MathML 2.0 plus SVG 1.1 DTD  ........................... --&gt;
        ///&lt;!-- URI: http://www.w3.org/2002/04/xhtml-math-svg/xhtml-math-svg.dtd
        ///--&gt;
        ///
        ///&lt;!-- XHTML 1.1 plus MathML 2.0 plus SVG 1.1 DTD
        ///
        ///     This is a prototype extension of XHTML 1.1 incorporating MathML 2.0
        ///     and SVG 1.1.
        ///
        ///     Copyright 2002 World Wide Web Consortium
        ///        (Massachusetts Institute of Technology, Institut National de
        ///         Recherche  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xhtml_math_svg_flat {
            get {
                return ResourceManager.GetString("xhtml_math_svg_flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ....................................................................... --&gt;
        ///&lt;!-- XHTML 1.1 DTD  ........................................................ --&gt;
        ///&lt;!-- file: xhtml11.dtd
        ///--&gt;
        ///
        ///&lt;!-- XHTML 1.1 DTD
        ///
        ///     This is XHTML, a reformulation of HTML as a modular XML application.
        ///
        ///     The Extensible HyperText Markup Language (XHTML)
        ///     Copyright 1998-2008 World Wide Web Consortium
        ///        (Massachusetts Institute of Technology, European Research Consortium
        ///         for Informatics and Mathematics, Kei [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xhtml11 {
            get {
                return ResourceManager.GetString("xhtml11", resourceCulture);
            }
        }
    }
}
